<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Content\ScriptFiles\MyCustomProperty.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Content\MeshFiles\remy.fbx" />
    <None Remove="Content\ShaderFiles\Basic.frag" />
    <None Remove="Content\ShaderFiles\Basic.vert" />
    <None Remove="Content\ShaderFiles\debugline.frag" />
    <None Remove="Content\ShaderFiles\debugline.vert" />
    <None Remove="Content\ShaderFiles\post.frag" />
    <None Remove="Content\ShaderFiles\post.vert" />
    <None Remove="Content\ShaderFiles\sdf.frag" />
    <None Remove="Content\ShaderFiles\sdf.vert" />
    <None Remove="Content\ShaderFiles\skybox.frag" />
    <None Remove="Content\ShaderFiles\skybox.vert" />
    <None Remove="Content\ShaderFiles\unlit.frag" />
    <None Remove="Content\TextureFiles\barrel.jpg" />
    <None Remove="Content\TextureFiles\brick.png" />
    <None Remove="Content\TextureFiles\brick_d.jpg" />
    <None Remove="Content\TextureFiles\brick_n.jpg" />
    <None Remove="Content\TextureFiles\dices.png" />
    <None Remove="Content\TextureFiles\DonutBaseColor.jpg" />
    <None Remove="Content\TextureFiles\house_brick.jpg" />
    <None Remove="Content\TextureFiles\house_windows.jpg" />
    <None Remove="Content\TextureFiles\house_wood.jpg" />
    <None Remove="Content\TextureFiles\IcingBaseColor.jpg" />
    <None Remove="Content\TextureFiles\panoramic-sea-back.png" />
    <None Remove="Content\TextureFiles\panoramic-sea-bottom.png" />
    <None Remove="Content\TextureFiles\panoramic-sea-front.png" />
    <None Remove="Content\TextureFiles\panoramic-sea-left.png" />
    <None Remove="Content\TextureFiles\panoramic-sea-right.png" />
    <None Remove="Content\TextureFiles\panoramic-sea-top.png" />
    <None Remove="Content\TextureFiles\panoramic-sky-back.png" />
    <None Remove="Content\TextureFiles\panoramic-sky-bottom.png" />
    <None Remove="Content\TextureFiles\panoramic-sky-front.png" />
    <None Remove="Content\TextureFiles\panoramic-sky-left.png" />
    <None Remove="Content\TextureFiles\panoramic-sky-right.png" />
    <None Remove="Content\TextureFiles\panoramic-sky-top.png" />
    <None Remove="Content\TextureFiles\point_light.png" />
    <None Remove="Content\TextureFiles\point_light_sprite.png" />
    <None Remove="Content\TextureFiles\wood.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Content\MeshFiles\remy.fbx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\ShaderFiles\unlit.frag">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\ShaderFiles\sdf.frag">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\ShaderFiles\sdf.vert">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\ShaderFiles\basic.frag">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\ShaderFiles\basic.vert">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\ShaderFiles\debugline.frag">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\ShaderFiles\debugline.vert">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\ShaderFiles\post.frag">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\ShaderFiles\post.vert">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\ShaderFiles\skybox.frag">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\ShaderFiles\skybox.vert">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\barrel.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\brick.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\brick_d.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\brick_n.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\dices.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\DonutBaseColor.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\house_brick.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\house_windows.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\house_wood.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\IcingBaseColor.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\panoramic-sea-back.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\panoramic-sea-bottom.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\panoramic-sea-front.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\panoramic-sea-left.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\panoramic-sea-right.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\panoramic-sea-top.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\panoramic-sky-back.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\panoramic-sky-bottom.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\panoramic-sky-front.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\panoramic-sky-left.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\panoramic-sky-right.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\panoramic-sky-top.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\point_light.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\point_light_sprite.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TextureFiles\3d\wood.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Jitter2" Version="2.8.5" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" />
    <PackageReference Include="Silk.NET.Assimp" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Maths" Version="2.23.0" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Content\ScriptFiles\Nodes\Models\States\State.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Content\ScriptFiles\Nodes\Props\InputControlProperty.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Content\ScriptFiles\Nodes\Props\StateProperty.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Content\AnimationFiles\remy.backflip.fbx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\AnimationFiles\remy.idle.fbx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\AnimationFiles\remy.jumping.fbx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\AnimationFiles\remy.jumping_jacks.fbx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\AnimationFiles\remy.walking.fbx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\AnimationFiles\remy.waving.fbx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\ConfigFiles\Fonts\roboto.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\ConfigFiles\Core\resourceFiles.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\ConfigFiles\Core\resources.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\ConfigFiles\ScriptPacks\scriptPacks.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\TextureFiles\Fonts\roboto.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
